export const testimonials = [
    {
        name: 'Maria Doe',
        role: 'Traveller',
        text: 'A home that perfectly blends sustainability with luxury until I discovered Ecoland Residence. From the moment I stepped into this community, I knew it was where I wanted to live. The commitment to eco-friendly living',
        image: 'assets/img/testimonial/testi_1_1.jpg',
        stars: 5,
        badge: '99',
    },
    {
        name: 'Angelina Rose',
        role: 'Traveller',
        text: 'A home that perfectly blends sustainability with luxury until I discovered Ecoland Residence. From the moment I stepped into this community, I knew it was where I wanted to live. The commitment to eco-friendly living',
        image: 'assets/img/testimonial/testi_1_1.jpg',
        stars: 5,
        badge: '99',
    },
    {
        name: 'John Smith',
        role: 'Traveller',
        text: 'A home that perfectly blends sustainability with luxury until I discovered Ecoland Residence. From the moment I stepped into this community, I knew it was where I wanted to live. The commitment to eco-friendly living',
        image: 'assets/img/testimonial/testi_1_1.jpg',
        stars: 5,
        badge: '99',
    },
    {
        name: 'John Smith',
        role: 'Traveller',
        text: 'A home that perfectly blends sustainability with luxury until I discovered Ecoland Residence. From the moment I stepped into this community, I knew it was where I wanted to live. The commitment to eco-friendly living',
        image: 'assets/img/testimonial/testi_1_1.jpg',
        stars: 5,
        badge: '99',
    },
    {
        name: 'John Smith',
        role: 'Traveller',
        text: 'A home that perfectly blends sustainability with luxury until I discovered Ecoland Residence. From the moment I stepped into this community, I knew it was where I wanted to live. The commitment to eco-friendly living',
        image: 'assets/img/testimonial/testi_1_1.jpg',
        stars: 5,
        badge: '99',
    },
    {
        name: 'John Smith',
        role: 'Traveller',
        text: 'A home that perfectly blends sustainability with luxury until I discovered Ecoland Residence. From the moment I stepped into this community, I knew it was where I wanted to live. The commitment to eco-friendly living',
        image: 'assets/img/testimonial/testi_1_1.jpg',
        stars: 5,
        badge: '99',
    },
];